version:  "3"
services:
  aoc-db:
    image: postgres:16
    container_name: aoc-db
    restart: always
    ports:
    - "127.0.0.1:54320:5432"
    expose:
    - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: aoc
      POSTGRES_USER: postgres
    volumes:
    - database:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "aoc", "-U", "postgres" ]
      interval: 5s
      timeout: 45s
      retries: 5
  aoc-migrations:
    image: sqitch/sqitch
    container_name: aoc-migrations
    command:
    - "deploy"
    depends_on:
      aoc-db:
        condition: service_healthy
    volumes:
    - ./:/repo
    - ${HOME}/:/home/
volumes:
  database:
